version: "1.0"

services:
    app:
        build:
            args:
                user: edgar
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: dapurkenyang-image
        container_name: dapurkenyang-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - dapurkenyang

    db:
        image: mysql:8.0
        container_name: dapurkenyang-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"
        networks:
            - dapurkenyang

#    frontend:
#        build: ./resources/js
#        volumes:
#            - ./resources/js:/app/resources/js
#        ports:
#            - "3000:3000"
#        depends_on:
#            - backend

    nginx:
        image: nginx:alpine
        container_name: dapurkenyang-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - dapurkenyang

volumes:
    mysql-data: # Persist your database data

networks:
    dapurkenyang:
        driver: bridge
