version: "1.0"

services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: dapurkenyang-image
        container_name: dapurkenyang-app
        restart: unless-stopped
        volumes:
            - ./:/var/www
        depends_on:
            - db
        user: "1000:1000"
        networks:
            - dapurkenyang
        deploy:
            resources:
                limits:
                    memory: 512M

    db:
        image: mysql:8.0
        container_name: dapurkenyang-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: dapur_kenyang
            MYSQL_ROOT_PASSWORD: dapurkenyang
            MYSQL_PASSWORD: dapurkenyang
            MYSQL_USER: dapurkenyang
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - dapurkenyang
        deploy:
            resources:
                limits:
                    memory: 2G

    redis:
        image: 'redis:alpine'
        container_name: dapurkenyang-redis
        restart: unless-stopped
        ports:
            - '6379:6379'
        volumes:
            - "./data/redis:/data"
        networks:
            - dapurkenyang
        deploy:
            resources:
                limits:
                    memory: 512M

    nginx:
        image: nginx:alpine
        container_name: dapurkenyang-nginx
        restart: unless-stopped
        depends_on:
            - app
        ports:
            - 4000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - dapurkenyang
        deploy:
            resources:
                limits:
                    memory: 128M

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: dapurkenyang-phpmyadmin
        ports:
            - "4001:80"
        environment:
            - PMA_HOST=db
        depends_on:
            - db
        networks:
            - dapurkenyang
        deploy:
            resources:
                limits:
                    memory: 128M

volumes:
    mysql-data:
    redis-data:

networks:
    dapurkenyang:
        driver: bridge
