version: "1.0"

services:
    app:
        build:
            args:
                user: edgar
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: dapurkenyang-image
        container_name: dapurkenyang-app
        restart: unless-stopped
        working_dir: /var/www/
        depends_on:
            - db
        volumes:
            - ./:/var/www
        networks:
            - dapurkenyang

    db:
        image: mysql:8.0
        container_name: dapurkenyang-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: dapur_kenyang
            MYSQL_ROOT_PASSWORD: dapurkenyang
            MYSQL_PASSWORD: dapurkenyang
            MYSQL_USER: dapurkenyang
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - dapurkenyang

    nginx:
        image: nginx:alpine
        container_name: dapurkenyang-nginx
        restart: unless-stopped
        depends_on:
            - app
        ports:
            - 4000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - dapurkenyang

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: dapurkenyang-phpmyadmin
        ports:
            - "4001:80"
        environment:
            - PMA_HOST=db
        depends_on:
            - db
        networks:
            - dapurkenyang

volumes:
    mysql-data:

networks:
    dapurkenyang:
        driver: bridge
